---
hosts:
  - name: kojibuilder1
    capacity: 16.0
    arches:
      - x86_64
      - i386
    channels:
      - default
      - livecd
  - name: koji-fedora28-builder
    capacity: 8.0
    arches:
      - x86_64
    channels:
      - createrepo
      - fedora
      - el8
