---
- hosts: localhost
  gather_facts: false
  collections:
    - ktdreyer.koji_ansible
  vars_files:
    - ../vars/hosts.yml
  tasks:
    - name: Define Koji hosts
      koji_host:
        name: "{{ host.name }}"
        state: "enabled"
        arches: "{{ host.arches }}"
        channels: "{{ host.channels }}"
        koji: 'koji'
      loop: "{{ hosts }}"
      loop_control:
        loop_var: host
