---
- hosts: localhost
  gather_facts: false
  collections:
    - ktdreyer.koji_ansible
  vars_files:
    - ../vars/users.yml
  tasks:
    - name: Set enabled users
      koji_user:
        name: "{{ user.name }}"
        state: "enabled"
        permissions: "{{ user.permissions }}"
        koji: 'koji'
      loop: "{{ enabled_users }}"
      loop_control:
        loop_var: user

    - name: Set disabled users
      koji_user:
        name: "{{ user.name }}"
        state: "disabled"
        permissions: []
        koji: 'koji'
      loop: "{{ disabled_users }}"
      loop_control:
        loop_var: user
